### ISSUE TITLE
Problem with System.eq?

### ISSUE THREAD

**Issue by petervanroy** [mozart/mozart2#255]
The {System.eq L M} is supposed to return false if L and M refer to different nodes in the store.
So if I do:
declare L in L=1|L
declare M in M=1|1|M
then {System.eq L M} should return false.
It actually does return true, which is wrong.

**Comment by eregon** [comment]
Looks to be an interesting bug: https://github.com/mozart/mozart2/blob/master/vm/vm/main/modules/modsystem.hh#L145-L152

**Comment by layus** [comment]
Could the nodes be effectively equal due to some optimization ? The code seems pretty straightforward : it compares internal node pointers.

**Comment by layus** [comment]
```oz
declare
L = 1|L
M = 1|1|M
{System.eq L M} = {Browse} % == false
```
turns out to be false on my computer. (Mozart Engine 2.0.0-alpha.0+build.**4138**.3739933-dirty)

**Comment by petervanroy** [comment]
On 15/01/15 20:02, Guillaume Maudoux wrote:
> declare
> L=  1|L
> M=  1|1|M
> {System.eq L M}=  {Browse}% == false
>
> turns out to be false on my computer. (Mozart Engine 
> 2.0.0-alpha.0+build.*4138*.3739933-dirty)
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/mozart/mozart2/issues/255#issuecomment-70141302>.
>
My version is:

Mozart Engine 2.0.0-alpha.0+build.3904.7aa7c52 (Wed, 9 Apr 2014 13:21:31 
+0200) playing Oz 3

running on Mac OS X 10.9.5.  Version probably too old?

Peter

**Comment by layus** [comment]
Commit 7aa7c529531dbaf3e2acc649ecf2296135f69b0c does not exist any more in the git history, so making a diff is difficult.
The diffs https://github.com/mozart/mozart2/compare/820031674cf339fb5779c8a40d060ec947556f9a...7aa7c529531dbaf3e2acc649ecf2296135f69b0c and https://github.com/mozart/mozart2/compare/820031674cf339fb5779c8a40d060ec947556f9a...master shows nothing that could lead to an error in System.eq.

@petervanroy Can you reproduce the problem ?
Also, you better install http://sourceforge.net/projects/mozart-oz/files/v2.0.0-alpha.0/mozart2-2.0.0-alpha.0%2Bbuild.4116.bdeaf6c-x86_64-darwin.dmg/download, because your version is behind the current version by more than 200 commits.
