### ISSUE TITLE
error: get_io_service

### ISSUE THREAD

**Issue by jvrn3** [mozart/mozart2#328]
Hello, I'm trying to install Mozart but got an error when running make.
Here is the error. How can I solve this?
```
[  5%] Building CXX object vm/boostenv/main/CMakeFiles/mozartvmboost.dir/boostvm.cc.o
/home/jvrn3/coding/mozart/mozart2-2.0.1-Source/vm/boostenv/main/boostvm.cc: In lambda function:
/home/jvrn3/coding/mozart/mozart2-2.0.1-Source/vm/boostenv/main/boostvm.cc:342:28: error: ‘class boost::asio::basic_deadline_timer<boost::posix_time::ptime>’ has no member named ‘get_io_service’
  342 |       preemptionTimerCopy->get_io_service().post([preemptionTimerCopy] {
      |                            ^~~~~~~~~~~~~~
make[2]: *** [vm/boostenv/main/CMakeFiles/mozartvmboost.dir/build.make:82: vm/boostenv/main/CMakeFiles/mozartvmboost.dir/boostvm.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:806: vm/boostenv/main/CMakeFiles/mozartvmboost.dir/all] Error 2
make: *** [Makefile:182: all] Error 2
```

**Comment by layus** [comment]
This error arises because you build with a newer version of boost.
You can see that the method has been [deprecated], and in your version of boost it simply does not exist anymore.
You can either try an older version (see the git logs, there are usually commits titled "Updating to boost XX.YY") or update the code to the new boost, and send a PR.

[deprecated]: https://www.boost.org/doc/libs/1_67_0/doc/html/boost_asio/reference/basic_socket/get_io_service.html

**Comment by jvrn3** [comment]
I was using the binary from https://github.com/mozart/mozart2/releases, but then I downloaded it directly from Github using git clone and it worked perfectly. 
Thank you!
